### ISSUE TITLE
Remove me from this repo's collaborators?

### ISSUE THREAD

**Issue by amcgregor** [nsasch/BachelorMP24#1]
Thanks!  Spring cleaning time for my GitHub account.  ;)

**Comment by ncadou** [comment]
I can't. You should ask Nick.

**Comment by amcgregor** [comment]
@ncadou You got messaged as a side-effect of ticket creation.  Sorry about that!  Hopefully Nick also got an e-mail about it.  XP

**Comment by ncadou** [comment]
Yeah I realized that right after hitting "send". :)

**Comment by nsasch** [comment]
Anybody else want to be removed?

@amcgregor removing you now.

**Comment by amcgregor** [comment]
Thanks!  :)

```
— Alice.
```
